// backup-app/src/App.tsx
import { useState, useCallback, useEffect } from 'react';
import { scanFolder, collectAllFiles } from './utils/scanner';
import { downloadAndSaveFileOnServer } from './utils/fileSaver';
import { extractUsername, checkIsCurrentUser, parseUserSections, extractAvatarUrl } from './utils/parser';
import { parseCookies, createCookiesFromSid, mergeCookies } from './utils/cookies';
import { fetchPageWithCookies } from './utils/http';
import { extractCKFromUrl, addCKToUrl } from './utils/url';
import { config } from './config';
import { saveCookies, loadCookies, saveUser, loadUser, clearCookies } from './utils/storage';
import { ProgressBar } from './components/ProgressBar';
import { formatBytes } from './utils/formatters';
import { isNewYearPeriod } from './utils/date';
import { StatusBadge } from './components/StatusBadge';
import { SectionSelector } from './components/SectionSelector';
import { SaveModeSelector } from './components/SaveModeSelector';
import { Sidebar } from './components/Sidebar';
import { FilesList } from './components/FilesList';
import type { BackupState, File, FileDownloadProgress } from './types';

function App() {
  const [sid, setSid] = useState('');
  const [fullCookies, setFullCookies] = useState<Record<string, string>>({});
  const [authCollapsed, setAuthCollapsed] = useState(false);
  const [state, setState] = useState<BackupState>({
    user: null,
    sections: [],
    selectedSections: [],
    saveMode: 'structure',
    savePath: '',
    rootFolder: null,
    scannedFiles: [],
    currentPage: 1,
    filesPerPage: 20,
    totalFiles: 0,
    downloadedFiles: 0,
    totalSize: 0,
    downloadedSize: 0,
      status: 'idle',
      fileProgress: new Map(),
      errors: [],
    });

  useEffect(() => {
    if (sid.trim() === '' && Object.keys(fullCookies).length === 0) {
      const savedCookies = loadCookies();
      const savedUser = loadUser();
      if (savedCookies) {
        try {
          const parsed = JSON.parse(savedCookies);
          if (parsed.sid) {
            setSid(parsed.sid);
            setFullCookies(parsed);
            if (savedUser) {
              setState(prev => ({ ...prev, user: savedUser }));
            }
          }
        } catch {
          const parsed = parseCookies(savedCookies);
          if (parsed.sid) {
            setSid(parsed.sid);
            setFullCookies(parsed);
            if (savedUser) {
              setState(prev => ({ ...prev, user: savedUser }));
            }
          }
        }
      } else if (savedUser && !state.user) {
        setState(prev => ({ ...prev, user: savedUser }));
      }
    }
  }, [sid, fullCookies, state.user]);

  const loadUserData = useCallback(async () => {
    const sidToUse = sid.trim();
    if (!sidToUse) {
      setState(prev => ({ ...prev, user: null, sections: [], selectedSections: [] }));
      return;
    }

    try {
      setState(prev => ({ ...prev, status: 'loading' }));
      
      let currentCookies = fullCookies.sid ? fullCookies : createCookiesFromSid(sidToUse);
      
      const response = await fetchPageWithCookies(config.baseUrl, currentCookies);
      let html = response.html;
      const newCookies = mergeCookies(currentCookies, response.cookies);
      currentCookies = newCookies;
      setFullCookies(currentCookies);
      
      let username = extractUsername(config.baseUrl, html);
      let isCurrentUser = checkIsCurrentUser(html);
      
      const deviceTypeMatch = html.match(/href="([^"]*device_type[^"]*)"/);
      const deviceTypeUrl = deviceTypeMatch ? deviceTypeMatch[1] : '';
      let ck = extractCKFromUrl(deviceTypeUrl) || extractCKFromUrl(config.baseUrl);
      
      console.log('Extracted username from main:', username);
      console.log('Is current user:', isCurrentUser);
      console.log('CK:', ck);
      console.log('Cookies from response:', response.cookies);
      
      let avatarUrl: string | undefined;
      let sectionsHtml = html;
      
      if (!username && response.cookies.user_id) {
        console.log('Username not found, trying to load profile by user_id:', response.cookies.user_id);
        try {
          const profileUrl = `${config.baseUrl}/mysite/index/`;
          const profileResponse = await fetchPageWithCookies(profileUrl, currentCookies);
          const profileCookies = mergeCookies(currentCookies, profileResponse.cookies);
          currentCookies = profileCookies;
          setFullCookies(currentCookies);
          username = extractUsername(profileUrl, profileResponse.html);
          sectionsHtml = profileResponse.html;
          console.log('Found username from profile page:', username);
        } catch (e) {
          console.log('Failed to load profile page:', e);
        }
      }
      
      if (username) {
        let profileUrl = `${config.baseUrl}/mysite/index/${username}/`;
        if (ck) {
          profileUrl = addCKToUrl(profileUrl, ck);
        }
        try {
          const profileResponse = await fetchPageWithCookies(profileUrl, currentCookies);
          sectionsHtml = profileResponse.html;
          const profileCookies = mergeCookies(currentCookies, profileResponse.cookies);
          currentCookies = profileCookies;
          setFullCookies(currentCookies);
          console.log('Loaded profile page:', profileUrl);
          avatarUrl = extractAvatarUrl(profileResponse.html);
          console.log('Avatar URL from profile page:', avatarUrl);
          
          if (!username) {
            username = extractUsername(profileUrl, profileResponse.html);
            console.log('Extracted username from profile page:', username);
          }
        } catch (e) {
          console.log('Failed to load profile, using main page');
          avatarUrl = extractAvatarUrl(html);
        }
      } else {
        avatarUrl = extractAvatarUrl(html);
      }
      
      const sections = parseUserSections(sectionsHtml, username, config.baseUrl);
      
      console.log('Parsed sections:', sections);
      
      const userData = { username, isCurrentUser, avatarUrl };
      saveUser(userData);
      saveCookies(JSON.stringify(currentCookies));
      
      setState(prev => ({
        ...prev,
        user: userData,
        sections,
        selectedSections: sections.map(s => s.id),
        status: 'idle',
      }));
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : 'Unknown error';
      setState(prev => ({
        ...prev,
        status: 'error',
        errors: [{ file: 'Load', error: errorMsg }],
      }));
    }
  }, [sid, fullCookies]);

  const handleLogout = useCallback(() => {
    clearCookies();
    setSid('');
    setFullCookies({});
    setState({
      user: null,
      sections: [],
      selectedSections: [],
      saveMode: 'structure',
      savePath: '',
      rootFolder: null,
      scannedFiles: [],
      currentPage: 1,
      filesPerPage: 20,
      totalFiles: 0,
      downloadedFiles: 0,
      totalSize: 0,
      downloadedSize: 0,
      status: 'idle',
      fileProgress: new Map(),
      errors: [],
    });
  }, []);

  const handleScan = useCallback(async () => {
    if (!state.user || state.selectedSections.length === 0) return;

    try {
      const cookiesObj = fullCookies.sid ? fullCookies : createCookiesFromSid(sid);
      setState(prev => ({ 
        ...prev, 
        status: 'scanning', 
        scannedFiles: [], 
        fileProgress: new Map(),
        downloadedFiles: 0,
        downloadedSize: 0,
        errors: [],
      }));

      const allFiles: File[] = [];
      const folderMap = new Map<string, { folder: any; sectionId: string }>();

      let updatedCookies = cookiesObj;
      
      for (const sectionId of state.selectedSections) {
        const section = state.sections.find(s => s.id === sectionId);
        if (!section) {
          console.log(`Section ${sectionId} not found`);
          continue;
        }

        console.log(`Scanning section: ${section.name} (${section.id})`);
        const rootFolder = await scanFolder(section.url, updatedCookies, '', (newCookies) => {
          updatedCookies = newCookies;
          setFullCookies(newCookies);
          saveCookies(JSON.stringify(newCookies));
        });
        const files = collectAllFiles(rootFolder);
        
        console.log(`Section ${section.name}: found ${files.length} files`);
        
        files.forEach(file => {
          file.path = `${section.folderName}/${file.path}`;
        });
        
        allFiles.push(...files);
        folderMap.set(sectionId, { folder: rootFolder, sectionId });
      }
      
      console.log(`Total files collected: ${allFiles.length}`);

      const fileProgressMap = new Map<string, FileDownloadProgress>();
      allFiles.forEach(file => {
        fileProgressMap.set(file.id, {
          fileId: file.id,
          fileName: `${file.name}${file.extension}`,
          progress: 0,
          speed: 0,
          status: 'pending',
        });
      });

      setState(prev => ({
        ...prev,
        scannedFiles: allFiles,
        totalFiles: allFiles.length,
        fileProgress: fileProgressMap,
        rootFolder: state.user ? {
          id: 'root',
          name: state.user.username,
          url: '',
          path: '',
          files: [],
          folders: Array.from(folderMap.values()).map(({ folder, sectionId }) => {
            const section = state.sections.find(s => s.id === sectionId);
            return {
              ...folder,
              name: section?.folderName || folder.name,
              path: section?.folderName || folder.path,
            };
          }),
        } : null,
        status: 'idle',
      }));
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : 'Unknown error';
      setState(prev => ({
        ...prev,
        status: 'error',
        errors: [...prev.errors, { file: 'Scan', error: errorMsg }],
      }));
    }
  }, [sid, fullCookies, state.user, state.sections, state.selectedSections]);

  const handleResetScan = useCallback(() => {
    setState(prev => ({
      ...prev,
      scannedFiles: [],
      fileProgress: new Map(),
      totalFiles: 0,
      downloadedFiles: 0,
      downloadedSize: 0,
      totalSize: 0,
      errors: [],
      rootFolder: null,
      currentPage: 1,
      status: 'idle',
    }));
  }, []);

  const downloadSingleFile = useCallback(async (
    file: File,
    cookiesObj: Record<string, string>
  ): Promise<void> => {
    if (!state.user) return;

    setState(prev => {
      const newProgress = new Map(prev.fileProgress);
      const progress = newProgress.get(file.id);
      if (progress) {
        newProgress.set(file.id, {
          ...progress,
          status: 'downloading',
          progress: 0,
          speed: 0,
        });
      }
      return { ...prev, fileProgress: newProgress, currentFile: file.name };
    });

    try {
      await downloadAndSaveFileOnServer(
        file,
        cookiesObj,
        state.user.username,
        state.saveMode,
        (progressPercent) => {
          setState(prev => {
            const newProgress = new Map(prev.fileProgress);
            const progress = newProgress.get(file.id);
            if (progress) {
              newProgress.set(file.id, {
                ...progress,
                progress: progressPercent,
                speed: 0,
              });
            }
            return { ...prev, fileProgress: newProgress };
          });
        }
      );

      setState(prev => {
        const newProgress = new Map(prev.fileProgress);
        const progress = newProgress.get(file.id);
        if (progress) {
          newProgress.set(file.id, {
            ...progress,
            progress: 100,
            speed: 0,
            status: 'completed',
          });
        }
        return {
          ...prev,
          fileProgress: newProgress,
          downloadedFiles: prev.downloadedFiles + 1,
        };
      });
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : 'Unknown error';
      setState(prev => {
        const newProgress = new Map(prev.fileProgress);
        const progress = newProgress.get(file.id);
        if (progress) {
          newProgress.set(file.id, {
            ...progress,
            status: 'error',
          });
        }
        return {
          ...prev,
          fileProgress: newProgress,
          errors: prev.errors.filter(e => e.file !== file.name).concat({ file: file.name, error: errorMsg }),
        };
      });
      throw error;
    }
  }, [state.user, state.saveMode]);

  const handleDownload = useCallback(async () => {
    if (state.scannedFiles.length === 0 || !state.user) return;

    try {
      const cookiesObj = fullCookies.sid ? fullCookies : createCookiesFromSid(sid);
      setState(prev => ({ ...prev, status: 'downloading' }));

      for (const file of state.scannedFiles) {
        const progress = state.fileProgress.get(file.id);
        if (progress?.status === 'completed') {
          continue;
        }
        try {
          await downloadSingleFile(file, cookiesObj);
        } catch (error) {
          console.error('Error downloading file:', error);
        }
      }

      setState(prev => ({ ...prev, status: 'completed' }));
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : 'Unknown error';
      setState(prev => ({
        ...prev,
        status: 'error',
        errors: [...prev.errors, { file: 'General', error: errorMsg }],
      }));
    }
  }, [sid, fullCookies, state.scannedFiles, state.user, downloadSingleFile]);

  const canScan = state.user && state.selectedSections.length > 0 && state.status === 'idle';
  const canDownload = state.scannedFiles.length > 0 && state.status === 'idle';
  const inProgress = ['loading', 'scanning', 'downloading', 'saving'].includes(state.status);
  const canLoad = sid.trim() && !state.user && state.status === 'idle';
  const showNewYearBg = isNewYearPeriod();

  return (
    <div 
      className="min-h-screen bg-dark-bg flex relative"
      style={showNewYearBg ? {
        backgroundImage: 'url(https://spaces.im/i/bg/newyear_dark.png?r=1)',
        backgroundAttachment: 'fixed',
        backgroundSize: 'cover',
        backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat',
      } : {}}
    >
      <div className="absolute inset-0 bg-dark-bg bg-opacity-80" />
      <div className="relative z-10 flex w-full">
        <Sidebar user={state.user} onLogout={handleLogout} />
        
        <div className="flex-1 p-8">
          <div className="max-w-4xl mx-auto">

          <div className="bg-dark-surface bg-opacity-50 backdrop-blur-sm rounded-lg border border-dark-border p-6 mb-6">
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <h2 className="text-lg font-semibold text-white">Авторизация</h2>
                <button
                  onClick={() => setAuthCollapsed(!authCollapsed)}
                  className="text-gray-400 hover:text-white transition-colors"
                >
                  {authCollapsed ? (
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                    </svg>
                  ) : (
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 15l7-7 7 7" />
                    </svg>
                  )}
                </button>
              </div>

              {!authCollapsed && (
                <>
                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">
                      SID
                    </label>
                    <input
                      type="text"
                      value={sid}
                      onChange={(e) => setSid(e.target.value)}
                      placeholder="Введите значение cookie sid"
                      disabled={inProgress || !!state.user}
                      className="w-full px-4 py-2 bg-dark-hover border border-dark-border rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent disabled:opacity-50 font-mono text-sm"
                    />
                    {Object.keys(fullCookies).length > 1 && (
                      <p className="text-xs text-gray-400 mt-2">
                        Получено cookies: {Object.keys(fullCookies).join(', ')}
                      </p>
                    )}
                  </div>

                  {!state.user && (
                    <button
                      onClick={() => loadUserData()}
                      disabled={!canLoad || inProgress}
                      className="w-full px-6 py-3 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-600 disabled:cursor-not-allowed text-white font-medium rounded-lg transition-colors"
                    >
                      Войти
                    </button>
                  )}
                </>
              )}

              {state.user && (
                <div className="pt-4 border-t border-dark-border space-y-4">
                  <SectionSelector
                    sections={state.sections}
                    selected={state.selectedSections}
                    onChange={(selected) => setState(prev => ({ ...prev, selectedSections: selected }))}
                    disabled={inProgress}
                  />

                  <SaveModeSelector
                    mode={state.saveMode}
                    onChange={(mode) => setState(prev => ({ ...prev, saveMode: mode }))}
                    disabled={inProgress}
                  />

                  <div className="flex gap-2">
                    {state.scannedFiles.length === 0 ? (
                      <button
                        onClick={handleScan}
                        disabled={!canScan || inProgress}
                        className="flex-1 px-6 py-3 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-600 disabled:cursor-not-allowed text-white font-medium rounded-lg transition-colors"
                      >
                        {state.status === 'scanning' ? 'Сканирование...' : 'Сканировать файлы'}
                      </button>
                    ) : (
                      <>
                        <button
                          onClick={handleResetScan}
                          disabled={inProgress}
                          className="px-4 py-3 bg-gray-600 hover:bg-gray-700 disabled:bg-gray-600 disabled:cursor-not-allowed text-white font-medium rounded-lg transition-colors"
                        >
                          Сбросить
                        </button>
                        <button
                          onClick={handleDownload}
                          disabled={!canDownload || inProgress}
                          className="flex-1 px-6 py-3 bg-green-600 hover:bg-green-700 disabled:bg-gray-600 disabled:cursor-not-allowed text-white font-medium rounded-lg transition-colors"
                        >
                          {state.status === 'downloading' && 'Скачивание...'}
                          {state.status === 'saving' && 'Сохранение...'}
                          {state.status === 'completed' && 'Завершено'}
                          {state.status === 'idle' && `Сохранить (${state.scannedFiles.length} файлов)`}
                          {state.status === 'error' && 'Ошибка'}
                        </button>
                      </>
                    )}
                  </div>
                </div>
              )}
            </div>
          </div>

          {state.scannedFiles.length > 0 && (
            <>
              <FilesList
                files={state.scannedFiles}
                currentPage={state.currentPage}
                filesPerPage={state.filesPerPage}
                fileProgress={state.fileProgress}
                onPageChange={(page) => setState(prev => ({ ...prev, currentPage: page }))}
                onRetryFile={(fileId) => {
                  const file = state.scannedFiles.find(f => f.id === fileId);
                  if (!file || !state.user) return;
                  
                  const cookiesObj = fullCookies.sid ? fullCookies : createCookiesFromSid(sid);
                  
                  downloadSingleFile(file, cookiesObj).catch(() => {
                    // Error already handled in downloadSingleFile
                  });
                }}
              />
            </>
          )}

          {state.user && state.status !== 'idle' && (
            <div className="bg-dark-surface bg-opacity-50 backdrop-blur-sm rounded-lg border border-dark-border p-6 mb-6">
              <div className="flex items-center justify-between mb-4">
      <div>
                  <h2 className="text-lg font-semibold text-white">Прогресс</h2>
                </div>
                <StatusBadge status={state.status} />
              </div>

              {state.totalFiles > 0 && (
                <div className="space-y-4">
                  <ProgressBar
                    value={state.downloadedFiles}
                    max={state.totalFiles}
                    label="Файлы"
                  />

                  {state.downloadedSize > 0 && (
                    <ProgressBar
                      value={state.downloadedSize}
                      max={state.totalSize || state.downloadedSize}
                      label="Размер"
                      formatValue={formatBytes}
                    />
                  )}

                  {state.currentFile && (
                    <div className="text-sm text-gray-400">
                      Текущий файл: <span className="text-white">{state.currentFile}</span>
                    </div>
                  )}
                </div>
              )}
            </div>
          )}

          {state.errors.length > 0 && (
            <div className="bg-dark-surface bg-opacity-50 backdrop-blur-sm rounded-lg border border-red-500 border-opacity-30 p-6">
              <h3 className="text-lg font-semibold text-red-400 mb-3">Ошибки</h3>
              <div className="space-y-2">
                {state.errors.map((error, index) => (
                  <div key={index} className="text-sm text-gray-300">
                    <span className="text-red-400">{error.file}:</span> {error.error}
                  </div>
                ))}
              </div>
            </div>
          )}
          </div>
        </div>
      </div>
      </div>
  );
}

export default App;

// backup-app/src/App.vue
<template>
  <div
    class="min-h-screen bg-dark-bg flex relative"
    :style="showNewYearBg ? newYearStyle : {}"
  >
    <div class="absolute inset-0 bg-dark-bg/80" />
    <div class="relative z-10 flex w-full">
      <Sidebar :user="authStore.user" @logout="handleLogout" />

      <div class="flex-1 p-8">
        <div class="max-w-4xl mx-auto">
          <div class="bg-dark-surface/50 backdrop-blur-sm rounded-lg border border-dark-border p-6 mb-6">
            <div class="space-y-4">
              <div class="flex items-center justify-between">
                <h2 class="text-lg font-semibold text-white">Авторизация</h2>
                <button
                  @click="authCollapsed = !authCollapsed"
                  class="text-gray-400 hover:text-white transition-colors"
                >
                  <svg
                    v-if="authCollapsed"
                    class="w-5 h-5"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M19 9l-7 7-7-7"
                    />
                  </svg>
                  <svg
                    v-else
                    class="w-5 h-5"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M5 15l7-7 7 7"
                    />
                  </svg>
                </button>
              </div>

              <div v-if="!authCollapsed">
                <div>
                  <label class="block text-sm font-medium text-gray-300 mb-2"> SID </label>
                  <input
                    v-model="displaySid"
                    type="text"
                    placeholder="Введите значение cookie sid"
                    :disabled="backupStore.inProgress || !!authStore.user"
                    class="w-full px-4 py-2 bg-dark-hover border border-dark-border rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent disabled:opacity-50 font-mono text-sm"
                  />
                  <p v-if="Object.keys(authStore.fullCookies).length > 1" class="text-xs text-gray-400 mt-2">
                    Получено cookies: {{ Object.keys(authStore.fullCookies).join(', ') }}
                  </p>
                </div>

                <button
                  v-if="!authStore.user"
                  @click="authStore.loadUserData()"
                  :disabled="!canLoad || backupStore.inProgress"
                  class="px-4 py-2 bg-gray-700 hover:bg-gray-600 disabled:bg-gray-800 disabled:cursor-not-allowed text-white text-sm font-normal rounded-md transition-colors"
                >
                  Войти
                </button>
              </div>

              <div v-if="authStore.user" class="pt-4 border-t border-dark-border space-y-4">
                <SectionSelector
                  :sections="authStore.sections"
                  :selected="authStore.selectedSections"
                  :disabled="backupStore.inProgress"
                  @update:selected="authStore.setSelectedSections"
                />

                <SaveModeSelector
                  :mode="backupStore.saveMode"
                  :disabled="backupStore.inProgress"
                  @update:mode="backupStore.setSaveMode"
                />

                <div class="flex gap-2">
                  <button
                    v-if="backupStore.scannedFiles.length === 0"
                    @click="backupStore.scan()"
                    :disabled="!backupStore.canScan || backupStore.inProgress"
                    class="flex-1 px-6 py-3 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-600 disabled:cursor-not-allowed text-white font-medium rounded-lg transition-colors"
                  >
                    {{ backupStore.status === 'scanning' ? 'Сканирование...' : 'Сканировать файлы' }}
                  </button>
                  <template v-else>
                    <button
                      @click="backupStore.resetScan()"
                      :disabled="backupStore.inProgress"
                      class="px-4 py-3 bg-gray-600 hover:bg-gray-700 disabled:bg-gray-600 disabled:cursor-not-allowed text-white font-medium rounded-lg transition-colors"
                    >
                      Сбросить
                    </button>
                    <button
                      @click="backupStore.download()"
                      :disabled="!backupStore.canDownload || backupStore.inProgress"
                      class="flex-1 px-6 py-3 bg-green-600 hover:bg-green-700 disabled:bg-gray-600 disabled:cursor-not-allowed text-white font-medium rounded-lg transition-colors"
                    >
                      <template v-if="backupStore.status === 'downloading'">Скачивание...</template>
                      <template v-else-if="backupStore.status === 'saving'">Сохранение...</template>
                      <template v-else-if="backupStore.status === 'completed'">Завершено</template>
                      <template v-else-if="backupStore.status === 'error'">Ошибка</template>
                      <template v-else>Сохранить ({{ backupStore.scannedFiles.length }} файлов)</template>
                    </button>
                  </template>
                </div>
              </div>
            </div>
          </div>

          <FilesList
            v-if="backupStore.scannedFiles.length > 0"
            :files="backupStore.scannedFiles"
            :current-page="backupStore.currentPage"
            :files-per-page="backupStore.filesPerPage"
            :file-progress="backupStore.fileProgress"
            :on-retry-file="backupStore.retryFile"
            @update:current-page="backupStore.setCurrentPage"
          />

          <div
            v-if="authStore.user && backupStore.status !== 'idle'"
            class="bg-dark-surface bg-opacity-50 backdrop-blur-sm rounded-lg border border-dark-border p-6 mb-6"
          >
            <div class="flex items-center justify-between mb-4">
              <div>
                <h2 class="text-lg font-semibold text-white">Прогресс</h2>
              </div>
              <StatusBadge :status="backupStore.status" />
            </div>

            <div v-if="backupStore.totalFiles > 0" class="space-y-4">
              <ProgressBar
                :value="backupStore.downloadedFiles"
                :max="backupStore.totalFiles"
                label="Файлы"
              />

              <ProgressBar
                v-if="backupStore.downloadedSize > 0"
                :value="backupStore.downloadedSize"
                :max="backupStore.totalSize || backupStore.downloadedSize"
                label="Размер"
                :format-value="formatBytes"
              />

              <div v-if="backupStore.currentFile" class="text-sm text-gray-400">
                Текущий файл: <span class="text-white">{{ backupStore.currentFile }}</span>
              </div>
            </div>
          </div>

          <FailedFilesList />

          <div
            v-if="backupStore.errors.length > 0 && !backupStore.hasFailedFiles"
            class="bg-dark-surface/50 backdrop-blur-sm rounded-lg border border-red-500/30 p-6"
          >
            <h3 class="text-lg font-semibold text-red-400 mb-3">Ошибки</h3>
            <div class="space-y-2">
              <div
                v-for="(error, index) in backupStore.errors"
                :key="index"
                class="text-sm text-gray-300"
              >
                <span class="text-red-400">{{ error.file }}:</span> {{ error.error }}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { useAuthStore } from '@/stores/auth'
import { useBackupStore } from '@/stores/backup'
import { isNewYearPeriod } from '@/utils/date'
import { formatBytes } from '@/utils/formatters'
import Sidebar from '@/components/Sidebar.vue'
import ProgressBar from '@/components/ProgressBar.vue'
import StatusBadge from '@/components/StatusBadge.vue'
import SectionSelector from '@/components/SectionSelector.vue'
import SaveModeSelector from '@/components/SaveModeSelector.vue'
import FilesList from '@/components/FilesList.vue'
import FailedFilesList from '@/components/FailedFilesList.vue'

const authStore = useAuthStore()
const backupStore = useBackupStore()

const authCollapsed = ref(false)

const showNewYearBg = computed(() => isNewYearPeriod())

const newYearStyle = {
  backgroundImage: 'url(https://spaces.im/i/bg/newyear_dark.png?r=1)',
  backgroundAttachment: 'fixed',
  backgroundSize: 'cover',
  backgroundPosition: 'center',
  backgroundRepeat: 'no-repeat',
}

const canLoad = computed(() => authStore.sid.trim() && !authStore.user && backupStore.status === 'idle')

const displaySid = computed({
  get: () => {
    if (authStore.user && authStore.sid.trim()) {
      return '*'.repeat(Math.min(authStore.sid.length, 50))
    }
    return authStore.sid
  },
  set: (value: string) => {
    authStore.sid = value
  },
})

function handleLogout() {
  authStore.logout()
  backupStore.resetScan()
}

onMounted(() => {
  authStore.loadSavedData()
})

watch(
  () => authStore.sid,
  () => {
    if (authStore.sid.trim() && !authStore.isLoading) {
      if (!authStore.user && backupStore.status !== 'loading') {
        authStore.loadUserData()
      } else if (authStore.user && authStore.sections.length === 0 && backupStore.status !== 'loading') {
        authStore.loadUserData()
      }
    }
  }
)
</script>
